server.port=8081

# H2 Database Console (optional, for local debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false 

# DataSource properties for H2 in-memory
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Spring Boot will automatically run schema.sql and data.sql
spring.sql.init.mode=always

server.forward-headers-strategy=framework

logging.level.org.springframework.web=TRACE
logging.level.org.apache.coyote.http11.Http11InputBuffer=DEBUG
logging.level.com.chenluo.vulnsqliexamplejava.controller=DEBUG 
