server.port=8081
spring.application.name=vuln-deserialize-cc-app

# Logging levels for debugging
logging.level.root=INFO
logging.level.com.tianshu.lab.vulnapps.deserializecc=DEBUG
logging.level.org.springframework.web=INFO